plugins {
    id 'com.android.application'
}

android {
    namespace 'br.com.ritmics'
    compileSdk 37

    defaultConfig {
        applicationId 'br.com.ritmics'
        minSdk 26
        targetSdk 36
        versionCode 5
        versionName '0.5.0'
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    lint {
        abortOnError true
    }
}

dependencies {
    implementation project(':core')
    implementation 'androidx.appcompat:appcompat:1.7.1'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test:runner:1.6.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
}
